imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        connections:
            default:
                driver:   %test_database_default_driver%
                host:     %test_database_default_host%
                port:     %test_database_default_port%
                dbname:   %test_database_default_name%
                user:     %test_database_default_user%
                password: %test_database_default_password%
                charset:  UTF8
            postgres:
                driver:   %test_database_postgres_driver%
                host:     %test_database_postgres_host%
                port:     %test_database_postgres_port%
                dbname:   %test_database_postgres_name%
                user:     %test_database_postgres_user%
                password: %test_database_postgres_password%
                charset:  UTF8

doctrine_mongodb:
    default_database: %test_mongodb_name%
    connections:
        default:
            server: mongodb://%test_mongodb_host%:%test_mongodb_port%
