<?php

namespace AppBundle\Document\Repository;
use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * HogeLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HogeLogRepository extends DocumentRepository
{
}