<?php

namespace UsePostgresqlBundle\Entity\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ShelfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShelfRepository extends EntityRepository
{
}
